"""empty message

Revision ID: 23d3d03e2d83
Revises: 
Create Date: 2017-06-20 00:56:16.464959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d3d03e2d83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paste',
    sa.Column('shortlink', sa.String(length=7), nullable=False),
    sa.Column('expiration_length_in_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paste_path', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('shortlink')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paste')
    # ### end Alembic commands ###
